services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "8080:80"
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

networks:
  laravel_network:
    external: true
