services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    hostname: laravel_app
    volumes:
      - ./src:/var/www
    networks:
      - laravel_network
    depends_on:
      - db
    working_dir: /var/www
    expose:
      - 9000

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    hostname: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    depends_on:
      - backend
    networks:
      - laravel_network

  db:
    image: mysql:5.7
    container_name: laravel_mysql
    hostname: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: 7959f2340d484d9a9fe62dbca01f27ce
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: 99bcaff6002c4e3dab901d82a62b8e7c
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
    external: true
